# Generated by Django 4.2.2 on 2023-06-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialhandles',
            name='social_id',
            field=models.CharField(default='blank', max_length=100),
        ),
        migrations.AddField(
            model_name='socialhandles',
            name='social_link',
            field=models.CharField(default='blank', max_length=500),
        ),
    ]
